In [1]:
import torchvision
myResnet50 = torchvision.models.resnet50(pretrained=True)
myResnet50

Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to /opt/ml/.cache/torch/hub/checkpoints/resnet50-19c8e357.pth


ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [4]:
import torch
import torch.nn.functional as fun
input = torch.rand((10,3))
print(input)
result = fun.log_softmax(input, 1)
print(result)

tensor([[0.2218, 0.3953, 0.3030],
        [0.8293, 0.3853, 0.9380],
        [0.8289, 0.9022, 0.3846],
        [0.6816, 0.5339, 0.1252],
        [0.9620, 0.2515, 0.3318],
        [0.1855, 0.5614, 0.1895],
        [0.0026, 0.8857, 0.1545],
        [0.4095, 0.0841, 0.0560],
        [0.4539, 0.6437, 0.9750],
        [0.6871, 0.5758, 0.4280]])
tensor([[-1.1860, -1.0125, -1.1048],
        [-1.0139, -1.4579, -0.9052],
        [-0.9996, -0.9263, -1.4440],
        [-0.8904, -1.0380, -1.4468],
        [-0.7050, -1.4155, -1.3352],
        [-1.2413, -0.8654, -1.2374],
        [-1.5222, -0.6391, -1.3703],
        [-0.8856, -1.2110, -1.2391],
        [-1.3592, -1.1694, -0.8380],
        [-0.9807, -1.0920, -1.2399]])


In [5]:
label = torch.randint(5, (3,), dtype=torch.int64)
print(label)

tensor([4, 2, 3])


In [6]:
print(torch.randn(3, 5, requires_grad=True))

tensor([[-0.4353, -0.2928,  1.9130, -0.7283, -0.7307],
        [ 0.4578,  1.2799,  0.2973,  0.7700,  0.6793],
        [ 0.0538,  0.1015,  1.5783, -0.7392, -0.6612]], requires_grad=True)


In [8]:
input = torch.randn(10, 18)
print(input)

tensor([[-0.5701, -0.7636,  0.4327,  0.3333,  1.7720, -0.2383,  0.5771,  0.5248,
         -0.0522,  0.8251,  0.8476, -1.0147,  1.7641,  0.5011,  0.3103, -0.3050,
         -0.9112,  0.2772],
        [ 1.2427, -1.2431, -1.4665, -0.4010, -0.2693, -1.6638,  0.5803,  0.0731,
         -1.8528,  1.5646,  2.1135,  0.9037, -1.8113,  1.0208, -0.5165, -1.3959,
          0.4219, -1.4287],
        [-0.2310,  0.3374, -1.1706,  1.2244,  0.0496,  0.4698,  0.0937, -0.0927,
         -0.4888,  0.2773,  2.1835,  0.1934, -0.2821,  0.7697,  0.0816,  0.7917,
         -0.6607,  0.7451],
        [-0.6033,  1.2791,  0.9219,  0.9769, -0.5384,  1.3166,  2.2959,  0.6573,
         -0.0790, -0.6744,  2.4957, -0.9679, -0.4686, -1.5526,  2.7729, -0.2493,
          0.5635,  0.9050],
        [ 0.1991,  2.2244, -1.3689, -0.9659, -0.5563,  0.6636, -1.2508,  0.7778,
          0.1315, -0.5185, -0.4030,  1.4112, -0.9784,  2.0891,  0.8618,  2.0822,
          0.6545,  1.4789],
        [-1.0500,  1.4641,  1.2874,  1.0653, -0.88

In [20]:
label = torch.randint(0, 17, (10,))
print(label)

tensor([16, 11,  3, 13, 10, 10, 10,  3,  9,  3])


In [11]:
_, y_hat = torch.max(input, -1)
print(y_hat)

tensor([ 4, 10, 10, 14,  1, 10,  6, 12,  7,  0])


In [21]:
preci = y_hat == label
preci

tensor([False, False, False, False, False,  True, False, False, False, False])

In [24]:
truePositive = sum(preci*1)/len(preci)
truePositive

tensor(0.1000)

In [25]:
from sklearn.metrics import accuracy_score, recall_score, precision_score, f1_score

In [29]:
print(f1_score(label, y_hat, average='micro'))

0.10000000000000002


In [31]:
import GPUtil

In [39]:
usage = GPUtil.showUtilization()

| ID | GPU | MEM |
------------------
|  0 |  0% |  0% |


In [45]:
gpus = GPUtil.getGPUs()
print(gpus)
for gpu in gpus:
    print(gpu)
    print(gpu.memoryUsed)
    print(gpu.memoryFree)
    print(gpu.display_active)