In [1]:
import os
import pandas as pd

In [2]:
test_dir = '/opt/ml/input/data/eval'
model_dir = '/opt/ml/code/out/models'
out_dir = '/opt/ml/code/out/submission'
try_cnt = 5

In [3]:
submission = pd.read_csv(os.path.join(test_dir, 'info.csv'))
submission

ImageID  ans
0      cbc5c6e168e63498590db46022617123f1fe1268.jpg    0
1      0e72482bf56b3581c081f7da2a6180b8792c7089.jpg    0
2      b549040c49190cedc41327748aeb197c1670f14d.jpg    0
3      4f9cb2a045c6d5b9e50ad3459ea7b791eb6e18bc.jpg    0
4      248428d9a4a5b6229a7081c32851b90cb8d38d0c.jpg    0
...                                             ...  ...
12595  d71d4570505d6af8f777690e63edfa8d85ea4476.jpg    0
12596  6cf1300e8e218716728d5820c0bab553306c2cfd.jpg    0
12597  8140edbba31c3a824e817e6d5fb95343199e2387.jpg    0
12598  030d439efe6fb5a7bafda45a393fc19f2bf57f54.jpg    0
12599  f1e0b9594ae9f72571f0a9dc67406ad41f2edab0.jpg    0

[12600 rows x 2 columns]

In [4]:
age_submission = pd.read_csv(os.path.join(out_dir, 'submission_5_age.csv'))
print(age_submission)
age_ans = age_submission.ans.values
print(age_ans)

                                            ImageID  ans
0      cbc5c6e168e63498590db46022617123f1fe1268.jpg    0
1      0e72482bf56b3581c081f7da2a6180b8792c7089.jpg    1
2      b549040c49190cedc41327748aeb197c1670f14d.jpg    1
3      4f9cb2a045c6d5b9e50ad3459ea7b791eb6e18bc.jpg    1
4      248428d9a4a5b6229a7081c32851b90cb8d38d0c.jpg    0
...                                             ...  ...
12595  d71d4570505d6af8f777690e63edfa8d85ea4476.jpg    1
12596  6cf1300e8e218716728d5820c0bab553306c2cfd.jpg    1
12597  8140edbba31c3a824e817e6d5fb95343199e2387.jpg    0
12598  030d439efe6fb5a7bafda45a393fc19f2bf57f54.jpg    1
12599  f1e0b9594ae9f72571f0a9dc67406ad41f2edab0.jpg    1

[12600 rows x 2 columns]
[0 1 1 ... 0 1 1]


In [5]:
gen_submission = pd.read_csv(os.path.join(out_dir, 'submission_5_gender.csv'))
print(gen_submission)
gen_ans = gen_submission.ans.values*3
print(gen_ans)

                                            ImageID  ans
0      cbc5c6e168e63498590db46022617123f1fe1268.jpg    1
1      0e72482bf56b3581c081f7da2a6180b8792c7089.jpg    1
2      b549040c49190cedc41327748aeb197c1670f14d.jpg    1
3      4f9cb2a045c6d5b9e50ad3459ea7b791eb6e18bc.jpg    1
4      248428d9a4a5b6229a7081c32851b90cb8d38d0c.jpg    1
...                                             ...  ...
12595  d71d4570505d6af8f777690e63edfa8d85ea4476.jpg    1
12596  6cf1300e8e218716728d5820c0bab553306c2cfd.jpg    1
12597  8140edbba31c3a824e817e6d5fb95343199e2387.jpg    1
12598  030d439efe6fb5a7bafda45a393fc19f2bf57f54.jpg    1
12599  f1e0b9594ae9f72571f0a9dc67406ad41f2edab0.jpg    1

[12600 rows x 2 columns]
[3 3 3 ... 3 3 3]


In [6]:
mask_submission = pd.read_csv(os.path.join(out_dir, 'submission_5_mask.csv'))
print(mask_submission)
mask_ans = mask_submission.ans.values*6
print(mask_ans)

                                            ImageID  ans
0      cbc5c6e168e63498590db46022617123f1fe1268.jpg    2
1      0e72482bf56b3581c081f7da2a6180b8792c7089.jpg    0
2      b549040c49190cedc41327748aeb197c1670f14d.jpg    2
3      4f9cb2a045c6d5b9e50ad3459ea7b791eb6e18bc.jpg    2
4      248428d9a4a5b6229a7081c32851b90cb8d38d0c.jpg    2
...                                             ...  ...
12595  d71d4570505d6af8f777690e63edfa8d85ea4476.jpg    0
12596  6cf1300e8e218716728d5820c0bab553306c2cfd.jpg    0
12597  8140edbba31c3a824e817e6d5fb95343199e2387.jpg    1
12598  030d439efe6fb5a7bafda45a393fc19f2bf57f54.jpg    0
12599  f1e0b9594ae9f72571f0a9dc67406ad41f2edab0.jpg    1

[12600 rows x 2 columns]
[12  0 12 ...  6  0  6]


In [7]:
ensemble_submission = mask_ans + age_ans + gen_ans
print(ensemble_submission)
print(max(ensemble_submission))
print(min(ensemble_submission))

[15  4 16 ...  9  4 10]
16
3


In [8]:
submission['ans'] = ensemble_submission

In [9]:
submission.to_csv(os.path.join(out_dir, f'submission_{str(5.5)}.csv'), index=False)

In [29]:
import datetime 
from pytz import timezone

now = datetime.datetime.now(timezone('Asia/Seoul'))
print(now)


2021-08-26 00:44:51.694408+09:00


In [13]:
class A:
    def __init__(self) -> None:
        print('hello in A')
    
    def do(self):
        print('do in A')

class B(A):
    def __init__(self) -> None:
        super().__init__()
        print('hello in B')
    
    def do(self):
        print('do in B')

inst_a = A()
inst_b = B()

print(isinstance(inst_a, A))
print(isinstance(inst_b, A))


    


hello in A
hello in A
hello in B
True
True


In [24]:
import model.model as M
import torch.nn as nn
r18 = M.__dict__['MyResnet18']
print(type(r18))
print(isinstance(r18, nn.Module))

<class 'torchvision.models.resnet.ResNet'>
True


In [34]:
import json
with open("./config.json") as f:
    data = json.load(f)
    print(data)
    print(type(data))

{'dirs': {'out': '${workspaceFolder}'}}
<class 'dict'>


In [35]:
import model.config as cf
cf.get()

'/opt/ml/code/model/config.py'

In [5]:
import torchvision
print(torchvision.models.__dict__['resnet34']())

ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    )
    (1): BasicBlock(
      (conv1): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
  